categories:
  - Metabolomics
description: "[Metabolomics][LC-MS][DIMS][Metabolite Annotation] BEAMSpy: Birmingham mEtabolite Annotation for Mass SpectroMetry (Python package)"
long_description: |
  BEAMSpy: Birmingham mEtabolite Annotation for Mass SpectroMetry (Python package)

  Repository-Maintainer: Ralf Weber (r.j.weber@bham.ac.uk)

  https://github.com/computational-metabolomics/beamspy
name: beamspy
owner: computational-metabolomics
remote_repository_url: https://github.com/computational-metabolomics/beamspy-galaxy
homepage_url: https://github.com/computational-metabolomics/beamspy-galaxy
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "[Metabolomics][LC-MS][DIMS][Metabolite Annotation] BEAMSpy: {{ tool_name }} {{ description }}"
