language: python
python:
 - "2.7"

before_install:
 - pip install --upgrade pip setuptools
 - pip install planemo
 - planemo --version

script:
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/beamspy
 - planemo test --conda_ensure_channels computational-metabolomics,iuc,bioconda,conda-forge,defaults ${TRAVIS_BUILD_DIR}/tools/beamspy
 
